extend type Mutation {
  """
  ✨ Insert a single `Equipment` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  equipment_insert(
    """
    Data object to insert into the table.
    """
    data: Equipment_Data!
  ): Equipment_KeyOutput! @fdc_generated(from: "Equipment", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Message` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  message_insert(
    """
    Data object to insert into the table.
    """
    data: Message_Data!
  ): Message_KeyOutput! @fdc_generated(from: "Message", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Order` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  order_insert(
    """
    Data object to insert into the table.
    """
    data: Order_Data!
  ): Order_KeyOutput! @fdc_generated(from: "Order", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Specification` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  specification_insert(
    """
    Data object to insert into the table.
    """
    data: Specification_Data!
  ): Specification_KeyOutput! @fdc_generated(from: "Specification", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Equipment` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  equipment_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Equipment_Data!]!
  ): [Equipment_KeyOutput!]! @fdc_generated(from: "Equipment", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Message` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  message_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Message_Data!]!
  ): [Message_KeyOutput!]! @fdc_generated(from: "Message", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Order` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  order_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Order_Data!]!
  ): [Order_KeyOutput!]! @fdc_generated(from: "Order", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Specification` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  specification_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Specification_Data!]!
  ): [Specification_KeyOutput!]! @fdc_generated(from: "Specification", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Equipment` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Equipment`.
  """
  equipment_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Equipment_Data!
  ): Equipment_KeyOutput! @fdc_generated(from: "Equipment", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Message` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Message`.
  """
  message_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Message_Data!
  ): Message_KeyOutput! @fdc_generated(from: "Message", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Order` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Order`.
  """
  order_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Order_Data!
  ): Order_KeyOutput! @fdc_generated(from: "Order", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Specification` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Specification`.
  """
  specification_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Specification_Data!
  ): Specification_KeyOutput! @fdc_generated(from: "Specification", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Equipment` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Equipment`.
  """
  equipment_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Equipment_Data!]!
  ): [Equipment_KeyOutput!]! @fdc_generated(from: "Equipment", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Message` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Message`.
  """
  message_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Message_Data!]!
  ): [Message_KeyOutput!]! @fdc_generated(from: "Message", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Order` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Order`.
  """
  order_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Order_Data!]!
  ): [Order_KeyOutput!]! @fdc_generated(from: "Order", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Specification` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Specification`.
  """
  specification_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Specification_Data!]!
  ): [Specification_KeyOutput!]! @fdc_generated(from: "Specification", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Equipment` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Equipment` or `null` if not found.
  """
  equipment_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Equipment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Equipment_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Equipment_Data!
  ): Equipment_KeyOutput @fdc_generated(from: "Equipment", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Message` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Message` or `null` if not found.
  """
  message_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Message_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Message_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Message_Data!
  ): Message_KeyOutput @fdc_generated(from: "Message", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Order` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Order` or `null` if not found.
  """
  order_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Order_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Order_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Order_Data!
  ): Order_KeyOutput @fdc_generated(from: "Order", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Specification` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Specification` or `null` if not found.
  """
  specification_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Specification_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Specification_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Specification_Data!
  ): Specification_KeyOutput @fdc_generated(from: "Specification", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Equipment` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  equipment_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Equipment_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Equipment_Data!
  ): Int! @fdc_generated(from: "Equipment", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Message` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  message_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Message_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Message_Data!
  ): Int! @fdc_generated(from: "Message", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Order` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  order_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Order_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Order_Data!
  ): Int! @fdc_generated(from: "Order", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Specification` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  specification_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Specification_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Specification_Data!
  ): Int! @fdc_generated(from: "Specification", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Equipment` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  equipment_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Equipment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Equipment_FirstRow
  ): Equipment_KeyOutput @fdc_generated(from: "Equipment", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Message` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  message_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Message_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Message_FirstRow
  ): Message_KeyOutput @fdc_generated(from: "Message", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Order` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  order_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Order_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Order_FirstRow
  ): Order_KeyOutput @fdc_generated(from: "Order", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Specification` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  specification_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Specification_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Specification_FirstRow
  ): Specification_KeyOutput @fdc_generated(from: "Specification", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Equipment` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  equipment_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Equipment_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Equipment", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Message` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  message_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Message_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Message", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Order` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  order_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Order_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Order", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Specification` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  specification_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Specification_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Specification", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
